#index:
#    path: /
#    controller: App\Controller\DefaultController::index


home:
    path: /
    controller: App\Controller\PublicController::home

login: 
    path: /login
    controller: App\Controller\PublicController::login

otro: 
    path: /otro
    controller: App\Controller\Private\OtroController::otro