#index:
#    path: /
#    controller: App\Controller\DefaultController::index


root:
    path: /home
    controller: App\Controller\PublicController::home

home:
    path: /home
    controller: App\Controller\PublicController::home

login: 
    path: /loginxxxxxxxxx
    controller: App\Controller\PublicController::login

otro: 
    path: /otro
    controller: App\Controller\Private\OtroController::otro