#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: home
        permanent: false

homeRedirect:
    path: /home
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /es/home
        permanent: false

home:
    path: /{_locale}/home
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    requirements:
        _locale: 'es|en|fr'
    defaults:
        # Obligatoria la ruta a la plantilla
        template:  'public/home.html.twig'
        # Opcionalmente puedes indicar al navegador opciones de cacheo
        maxAge:    86400
        sharedAge: 86400
        # opcionalmente puedes pasar datos a la plantilla
        context:
            site_name: 'ACME'
            theme: 'dark'

login: 
    path: /loginxxxxxxxxx
    controller: App\Controller\PublicController::login

otro: 
    path: /otro
    controller: App\Controller\Private\OtroController::otro